version: '3'
services:
    web:
        build: .
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: cratesfyi
            POSTGRES_PASSWORD: password
