---

on: [push, pull_request]
name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Install stable Rust
        run: rustup update stable && rustup default stable

      - name: Build docs.rs
        run: cargo build

      - name: Test docs.rs
        run: cargo test -- --test-threads=1

      - name: Install HTML parser
        # TODO: don't hardcode this for amd64
        run: >
            wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip &&
            [ "$(sha256sum pup_v0.4.0_linux_amd64.zip | cut -d ' ' -f 1)" =
            ec3d29e9fb375b87ac492c8b546ad6be84b0c0b49dab7ff4c6b582eac71ba01c ] &&
            unzip pup_v0.4.0_linux_amd64.zip

      - name: Cache Rustwide directory
        uses: actions/cache@v1
        with:
          key: always
          path: .rustwide-docker

      - name: Setup local docker directory
        run: >
            mkdir -p ignored/docker &&
            sudo systemctl stop docker &&
            sudo rm -rf /var/lib/docker &&
            sudo ln -sf "$(realpath ignored/docker)" /var/lib/docker &&
            sudo systemctl start docker

      - name: Cache docker directory
        uses: actions/cache@v1
        with:
          key: always
          path: ignored/docker

      - name: Test docs.rs more thoroughly
        run: cp .env.sample .env && PATH="$PATH:." ./test.sh

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Build the Docker image
        run: docker build -t docsrs .

      - name: Upload the Docker image to ECR
        uses: rust-lang/simpleinfra/github-actions/upload-docker-image@master
        with:
          image: docsrs
          repository: docsrs
          region: us-west-1
          aws_access_key_id: "${{ secrets.aws_access_key_id }}"
          aws_secret_access_key: "${{ secrets.aws_secret_access_key }}"
        if: github.ref == 'refs/heads/master'
